# Screen stream configuration

paths:
  screen:
    runOnInit: ${FFMPEG_BIN} -f x11grab -video_size 3840x2400 -framerate 30 -i :0.0 -c:v h264_nvenc -preset llhp -g 30 -pix_fmt yuv420p -f rtsp -rtsp_transport tcp rtsp://localhost:8553/screen
    runOnInitRestart: yes