- name: install via apt
  hosts: all
  become: true
  tasks:
    - name: Install ffmpeg and pipewire
      ansible.builtin.apt:
        name: 
          - pipewire
          - pipewire-bin
          - pipewire-pulse
          - pipewire-jack
          - libpipewire-0.3-dev
          - ffmpeg
        state: present
        update_cache: no
