- name: copy mediamtx config file to all hosts
  hosts: lab_machines
  become: false
  tasks:
    - name: copy file
      ansible.builtin.file:
        path: /data/multistream/screen
        state: directory
        owner: participant
        group: participant
        mode: '0777'
