- name: install via apt
  hosts: all
  become: true
  tasks:
    - name: Install trash_cli
      ansible.builtin.apt:
        name: 
          - trash-cli
        state: present
        update_cache: no
