- name: Copy 'stream' folder contents to Synology guest share
  hosts: prr_hosts
  gather_facts: yes
  vars:
    synology_server: 192.168.10.201
    synology_share: datadump/prr_data/raw
    garden_dir: /data/garden/
    cyclesix_dir: /data/cyclesix

  tasks:
    - name: Random delay to avoid Synology collisions
      ansible.builtin.pause:
        seconds: "{{ 1 + (ansible_hostname | hash('sha256') | int(base=16) % 5) }}"
    - name: Upload str contents to existing host folder on Synology
      ansible.builtin.command: >
        smbclient //{{ synology_server }}/{{ synology_share }} -N -c "lcd {{ garden_dir }}; cd {{ ansible_hostname }}; prompt; recurse; mput *"
      args:
        chdir: "{{ garden_dir }}"
      async: 600
      poll: 0
    - name: New Random delay to avoid Synology collisions
      ansible.builtin.pause:
        seconds: "{{ 1 + (ansible_hostname | hash('sha256') | int(base=16) % 5) }}"
    - name: Upload stream contents to existing host folder on Synology
      ansible.builtin.command: >
        smbclient //{{ synology_server }}/{{ synology_share }} -N -c "lcd {{ cyclesix_dir }}; cd {{ ansible_hostname }}; prompt; recurse; mput *"
      args:
        chdir: "{{ cyclesix_dir }}"
      async: 600
      poll: 0
