- name: Run shell scripts on tianyi group
  hosts: whitepaper
  become: no
  ignore_unreachable: yes
  vars:
    script_dir: /home/participant/Desktop
    ansible_timeout: 10

  tasks:
    - name: Run owl script in background
      shell: "nohup {{ script_dir }}/owl_c4_ffmpeg_with_overlay.sh > /tmp/owl.log 2>&1 & echo $! > /tmp/owl_pid.txt"
      timeout: 15

    - name: Read PIDs
      slurp:
        src: "{{ item }}"
      loop:
        - /tmp/owl_pid.txt
      register: pid_files

    - name: Save PIDs to local file
      local_action:
        module: copy
        content: "{{ pid_files.results[0].content | b64decode | trim }},{{ pid_files.results[1].content | b64decode | trim }}"
        dest: ./session_pids.txt

    - name: Show captured PIDs
      debug:
        msg: "owl PID={{ pid_files.results[0].content | b64decode | trim }}"
