- name: Shutdown all hosts using systemd
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Power off the host
      ansible.builtin.systemd:
        name: poweroff.target
        state: restarted   # or "stopped" also works
      async: 0
      poll: 0

